name: Run test suite
on: push

jobs:
  run-tests:
    name: Run php unit test.
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Running composer install
        run: composer install
      - name: Create a sqlite file
        run: touch database/database.sqlite
      - name: Running php unit test cases
      # this command did not work as the github actions failed and recommended to run the "./vendor/bin/pest"
        # run: ./vendor/bin/phpunit tests
        # run: ./vendor/bin/pest tests
        run: php artisan test
